import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Provider from "@/components/Provider";


const inter = Inter({ subsets: ["latin"],  variable: "--font-sans",});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({

  children,

}: Readonly<{

  children: React.ReactNode;

}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased scrollbar-thin scrollbar-w-3 scrollbar-h-3 scrollbar-thumb-rounded-full",
          inter.variable
        )}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
